#!/usr/bin/perl
#$ -cwd
#$ -q high_mem
#$ -pe mpich 20
#$ -l mem_free=150G

REF=/nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Trinity_Assembly/???
 
#101
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_101/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_101_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_101/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_101_2.t-20.FQT.2.fastq   

wait
#102
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_102/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_102_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_102/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_102_2.t-20.FQT.2.fastq

wait
#103
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_103/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_103_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_103/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_103_2.t-20.FQT.2.fastq

wait
#104
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_104/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_104_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_104/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_104_2.t-20.FQT.2.fastq

wait
#105
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_105/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_105_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_105/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_105_1.t-20.FQT.2.fastq

wait
#106
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_106/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_106_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_106/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_106_2.t-20.FQT.2.fastq

wait
#107
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_107/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_107_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_107/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_107_2.t-20.FQT.2.fastq

wait
#108
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_108/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_108_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_108/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_108_2.t-20.FQT.2.fastq

wait
#109
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_109/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_109_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_109/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_109_2.t-20.FQT.2.fastq

wait
#110
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_110/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_110_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_110/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_110_2.t-20.FQT.2.fastq

wait
#111
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_111/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_111_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_111/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_111_2.t-20.FQT.2.fastq

wait
#112
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_112/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_112_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_112/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_112_2.t-20.FQT.2.fastq

wait
#113
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_113/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_113_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_113/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_113_2.t-20.FQT.2.fastq

wait
#114
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_114/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_114_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_114/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_114_2.t-20.FQT.2.fastq

wait 
#115
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_115/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_115_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_115/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_115_2.t-20.FQT.2.fastq

wait
#116
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_116/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_116_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_116/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_116_2.t-20.FQT.2.fastq

wait
#117
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_117/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_117_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_117/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_117_2.t-20.FQT.2.fastq

wait
#118
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_118/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_118_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_118/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_118_2.t-20.FQT.2.fastq

wait
#119
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_119/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_119_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_119/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_119_2.t-20.FQT.2.fastq

wait
#120
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_120/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_120_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_120/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_120_2.t-20.FQT.2.fastq

wait
#121
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_121/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_121_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_121/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_121_2.t-20.FQT.2.fastq

wait
#122
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_122/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_122_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_122/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_122_2.t-20.FQT.2.fastq

wait
#123
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_123/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_123_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_123/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_123_2.t-20.FQT.2.fastq

wait
#124
/usr/local/bin/trinityrnaseq_r20140717/util/align_and_estimate_abundance.pl --seqType fq --est_method alignment_based \
--output_dir /nobackup/data9/Pseudomonas_putida_transcriptome_project/Analysis/Downstream_analysis/Abundance_estimation/RSEM/Analysis \
--est_method RSEM --aln_method bowtie2 -SS_lib_type FR --thread_count 20 --trinity-mode \
--transcripts $REF \
--left /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_124/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_124_1.t-20.FQT.2.fastq \
--right /nobackup/data9/Pseudomonas_putida_transcriptome_project/data/P2201_124/150702_AC6U4VANXX/8_150702_AC6U4VANXX_P2201_124_2.t-20.FQT.2.fastq

wait
echo "done with abundance estimation"
date
