#!/bin/bash
#$ -cwd
#$ -q high_mem
#$ -pe mpich 20
#$ -o /state/partition2/Alexheinz/ref_2/stdout_trinity.txt
#$ -e /state/partition2/Alexheinz/ref_2/stderr_trinity.txt
#$ -S /bin/bash
#$ -l mem_free=150G


/usr/local/bin/trinityrnaseq_r20140717/Trinity --genome_guided_use_bam /state/partition2/Alexheinz/ref_2.coordSorted.bam --seqType fq --genome_guided_max_intron 0 --left /state/partition2/Alexheinz/pair1.fastq --right /state/partition2/Alexheinz/pair2.fastq --SS_lib_type FR --JM 150G --genome_guided_CPU 20 --output /state/partition2/Alexheinz/ref_2

echo "Done with Reference based Trinity assembly"
date
