#!/bin/bash

#$ -S /bin/bash
#$ -q node0
#$ -pe mpich 2

F=5
T=20

for dir in /nobackup/data11/Pseudomonas_putida_transcriptome_project/data/*
do
	cd $dir/*

#	gunzip $(ls *_1.fastq.gz) &
#	gunzip $(ls *_2.fastq.gz)
#	wait

	file1=$PWD/$(ls *_1.t-20.FQT.fastq)
	file2=$PWD/$(ls *_2.t-20.FQT.fastq)
	
    	fastx_trimmer -Q33 -i $file1 -f $F -o "${file1%.fastq}.2.fastq" &
	fastx_trimmer -Q33 -i $file2 -f $F -o "${file2%.fastq}.2.fastq"
        wait
	
#	fastq_quality_trimmer -Q33 -t $T -i "${file1%.fastq}.FXT.fastq" -o "${file1%.fastq}.t-${T}.FQT.fastq" &
#	fastq_quality_trimmer -Q33 -t $T -i "${file2%.fastq}.FXT.fastq" -o "${file2%.fastq}.t-${T}.FQT.fastq"
#	wait

	# Quality check
	fastqc "${file1%.fastq}.2.fastq" &
	fastqc "${file2%.fastq}.2.fastq"

done
